<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>LlamaPure</AssemblyName>
    <RootNamespace>LlamaPure</RootNamespace>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Authors>taqu</Authors>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/taqu/LlamaPure</RepositoryUrl>
    <PackageTags>LLama;LLM</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="llama\**" />
    <EmbeddedResource Remove="llama\**" />
    <None Remove="llama\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ggml-base.dll" />
    <None Remove="ggml-cpu.dll" />
    <None Remove="ggml.dll" />
    <None Remove="llama.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="build\LlamaPure.targets" Pack="true" PackagePath="build\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="runtimes\win-x64\native\*.*" Pack="true" PackagePath="runtimes\win-x64\native" />
  </ItemGroup>
</Project>
